name: Deploy RentWise Client

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-deploy-client:
    runs-on: windows-latest
    name: Build and Deploy RentWise Client
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.401'

      - name: Restore dependencies
        run: dotnet restore RentWise/RentWise.csproj

      - name: Build project
        run: dotnet build RentWise/RentWise.csproj --configuration Release --no-restore

      - name: Publish project
        run: dotnet publish RentWise/RentWise.csproj -c Release -o ./publish/rentwise

      - name: List published files
        run: Get-ChildItem -Path ./publish/rentwise/*
        shell: pwsh

      - name: Compress Published Files
        run: Compress-Archive -Path ./publish/rentwise/* -DestinationPath ./publish/rentwise.zip

      - name: Deploy to VPS
        run: |
          $pass = "${{ secrets.DEPLOY_PASS }}" | ConvertTo-SecureString -AsPlainText -Force
          $user = "${{ secrets.DEPLOY_USER }}"
          $cred = New-Object System.Management.Automation.PSCredential ($user, $pass)
          $session = New-PSSession -ComputerName "92.205.231.160" -Credential $cred -UseSSL -SessionOption (New-PSSessionOption -SkipCACheck -SkipCNCheck)
          Copy-Item -Path "./publish/rentwise.zip" -Destination "C:\\rentwise\\client" -ToSession $session
          Invoke-Command -Session $session -ScriptBlock {
            Expand-Archive -Path "C:\\rentwise\\client\\rentwise.zip" -DestinationPath "C:\\rentwise\\client"
            cd "C:\\rentwise\\client" 
            dotnet RentWise.dll
          }
          Remove-PSSession $session
        shell: pwsh

      - name: Clean up local artifacts
        run: Remove-Item -Path ./publish/rentwise.zip
        shell: pwsh
