name: Deploy RentWise Application

on:
  push:
    branches:
      - master  # Adjust this to your deployment branch

jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up MSBuild path
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Restore NuGet packages
      run: nuget restore RentWise.sln

    - name: Build Solution
      run: msbuild RentWise.sln /p:Configuration=Release /p:DeployOnBuild=true /p:PublishProfile=FolderProfile

    - name: Install WinSCP
      run: choco install winscp

    - name: Upload RentWise files
      shell: powershell
      run: |
        $scpPath = "C:\Program Files (x86)\WinSCP\WinSCP.com"
        & $scpPath /ini=nul /log="C:\deploy.log" /command `
          "open sftp://$env:VPS_USERNAME:$env:VPS_PASSWORD@$env:VPS_ADDRESS/ -hostkey=`"*`"" `
          "put RentWise/bin/Release/netcoreapp3.1/publish/* /rentwise/client/ -preservetime" `
          "exit"

    - name: Upload RentWise.Agent files
      shell: powershell
      run: |
        $scpPath = "C:\Program Files (x86)\WinSCP\WinSCP.com"
        & $scpPath /ini=nul /log="C:\deploy.log" /command `
          "open sftp://$env:VPS_USERNAME:$env:VPS_PASSWORD@$env:VPS_ADDRESS/ -hostkey=`"*`"" `
          "put RentWise.Agent/bin/Release/netcoreapp3.1/publish/* /rentwise/admin/ -preservetime" `
          "exit"
      env:
        VPS_USERNAME: ${{ secrets.VPS_USERNAME }}
        VPS_PASSWORD: ${{ secrets.VPS_PASSWORD }}
        VPS_ADDRESS: ${{ secrets.VPS_ADDRESS }}
