name: Deploy .NET Applications

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-deploy-rentwise:
    runs-on: windows-latest
    name: Build and Deploy RentWise (Client)
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x'

    - name: Restore dependencies
      run: dotnet restore RentWise/RentWise.csproj

    - name: Build RentWise
      run: dotnet build --configuration Release --no-restore RentWise/RentWise.csproj

    - name: Publish RentWise
      run: dotnet publish -c Release -o ./publish RentWise/RentWise.csproj

    - name: Stop existing RentWise Client instance on VPS
      run: |
        ssh sethoo@92.205.231.160 "taskkill /IM RentWise.dll /F || echo 'No existing RentWise Client process running'"

    - name: Deploy RentWise Client to VPS
      run: |
        $DEPLOY_PATH="C:/rentwise/client"
        ssh sethoo@92.205.231.160 "mkdir -p $DEPLOY_PATH"
        scp -r ./publish/* sethoo@92.205.231.160:$DEPLOY_PATH
        ssh sethoo@92.205.231.160 "cd $DEPLOY_PATH && dotnet RentWise.dll"
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

  build-and-deploy-agent:
    runs-on: windows-latest
    name: Build and Deploy RentWise.Agent (Admin)
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x'

    - name: Restore dependencies
      run: dotnet restore RentWise.Agent/RentWise.Agent.csproj

    - name: Build RentWise.Agent
      run: dotnet build --configuration Release --no-restore RentWise.Agent/RentWise.Agent.csproj

    - name: Publish RentWise.Agent
      run: dotnet publish -c Release -o ./publish RentWise.Agent/RentWise.Agent.csproj

    - name: Stop existing RentWise Admin instance on VPS
      run: |
        ssh sethoo@92.205.231.160 "taskkill /IM RentWise.Agent.dll /F || echo 'No existing RentWise Admin process running'"

    - name: Deploy RentWise Admin to VPS
      run: |
        $DEPLOY_PATH="C:/rentwise/admin"
        ssh sethoo@92.205.231.160 "mkdir -p $DEPLOY_PATH"
        scp -r ./publish/* sethoo@92.205.231.160:$DEPLOY_PATH
        ssh sethoo@92.205.231.160 "cd $DEPLOY_PATH && dotnet RentWise.Agent.dll"
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
