name: Deploy .NET Applications

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: windows-latest
    name: Build and Deploy Applications
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x'

    - name: Restore dependencies
      run: |
        dotnet restore RentWise/RentWise.csproj
        dotnet restore RentWise.Agent/RentWise.Agent.csproj

    - name: Build projects
      run: |
        dotnet build --configuration Release --no-restore RentWise/RentWise.csproj &
        dotnet build --configuration Release --no-restore RentWise.Agent/RentWise.Agent.csproj
      wait

    - name: Publish projects
      run: |
        dotnet publish RentWise/RentWise.csproj -c Release -o ./publish/rentwise &
        dotnet publish RentWise.Agent/RentWise.Agent.csproj -c Release -o ./publish/rentwise-agent
      wait

    - name: Compress Published Files
      run: |
        Compress-Archive -Path ./publish/rentwise/* -DestinationPath ./publish/rentwise.zip
        Compress-Archive -Path ./publish/rentwise-agent/* -DestinationPath ./publish/rentwise-agent.zip

    - name: Deploy to VPS using rsync
      run: |
        $DEPLOY_PATH_RENTWISE="C:/rentwise/client"
        $DEPLOY_PATH_AGENT="C:/rentwise/admin"
        
        ssh sethoo@92.205.231.160 "mkdir -p $DEPLOY_PATH_RENTWISE $DEPLOY_PATH_AGENT"

        # Transfer files using rsync for incremental deployment
        rsync -avz -e "ssh -i $env:SSH_PRIVATE_KEY" ./publish/rentwise.zip sethoo@92.205.231.160:$DEPLOY_PATH_RENTWISE &
        rsync -avz -e "ssh -i $env:SSH_PRIVATE_KEY" ./publish/rentwise-agent.zip sethoo@92.205.231.160:$DEPLOY_PATH_AGENT
        wait

        # Unzip on the server and deploy
        ssh sethoo@92.205.231.160 "Expand-Archive -Path $DEPLOY_PATH_RENTWISE/rentwise.zip -DestinationPath $DEPLOY_PATH_RENTWISE"
        ssh sethoo@92.205.231.160 "Expand-Archive -Path $DEPLOY_PATH_AGENT/rentwise-agent.zip -DestinationPath $DEPLOY_PATH_AGENT"

        # Start the applications concurrently
        ssh sethoo@92.205.231.160 "cd $DEPLOY_PATH_RENTWISE && dotnet RentWise.dll &"
        ssh sethoo@92.205.231.160 "cd $DEPLOY_PATH_AGENT && dotnet RentWise.Agent.dll"
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
