name: Deploy RentWise Admin

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-deploy-admin:
    runs-on: windows-latest
    name: Build and Deploy RentWise Admin
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'

      - name: Restore dependencies
        run: dotnet restore RentWise.Agent/RentWise.Agent.csproj

      - name: Build project
        run: dotnet build RentWise.Agent/RentWise.Agent.csproj --configuration Release --no-restore

      - name: Publish project
        run: dotnet publish RentWise.Agent/RentWise.Agent.csproj -c Release -o ./publish/rentwise-agent

      - name: Compress Published Files
        run: Compress-Archive -Path ./publish/rentwise-agent/* -DestinationPath ./publish/rentwise-agent.zip

      - name: Deploy to VPS
        run: |
          $password = "${{ secrets.DEPLOY_PASS }}" | ConvertTo-SecureString -AsPlainText -Force
          $username = "${{ secrets.DEPLOY_USER }}"
          $cred = New-Object System.Management.Automation.PSCredential ($username, $password)
          $session = New-PSSession -ComputerName 92.205.231.160 -Credential $cred
          Copy-Item -Path "./publish/rentwise-agent.zip" -Destination "C:\\rentwise\\admin" -ToSession $session
          Invoke-Command -Session $session -ScriptBlock {
            Expand-Archive -Path "C:\\rentwise\\admin\\rentwise-agent.zip" -DestinationPath "C:\\rentwise\\admin"
            cd "C:\\rentwise\\admin" 
            dotnet RentWise.Agent.dll
          }
          Remove-PSSession $session
        shell: pwsh

      - name: Clean up local artifacts
        run: Remove-Item -Path ./publish/rentwise-agent.zip
        shell: pwsh
