name: Deploy RentWise Application

on:
  push:
    branches:
      - master  # Set this to the branch you want to deploy from

jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up MSBuild path
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Restore dependencies
      run: nuget restore RentWise.sln

    - name: Build Solution
      run: msbuild RentWise.sln /p:Configuration=Release /p:DeployOnBuild=true /p:PublishProfile=FolderProfile

    - name: Deploy RentWise
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.VPS_ADDRESS }}
        username: ${{ secrets.VPS_USERNAME }}
        password: ${{ secrets.VPS_PASSWORD }}
        port: 22
        source: "RentWise/bin/Release/netcoreapp3.1/publish/*"
        target: "C:/rentwise/client/"

    - name: Deploy RentWise.Agent
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.VPS_ADDRESS }}
        username: ${{ secrets.VPS_USERNAME }}
        password: ${{ secrets.VPS_PASSWORD }}
        port: 22
        source: "RentWise.Agent/bin/Release/netcoreapp3.1/publish/*"
        target: "C:/rentwise/admin/"
